### ISSUE TITLE
Running php darkeagle.php is doing exactly like clearing the terminal window

### ISSUE THREAD

**Issue by jordantsap** [nandydark/DARK-EAGLE#1]
![simplescreenrecorder-2020-01-14_20 34 11](https://user-images.githubusercontent.com/4333386/72371781-0bab5a80-36d3-11ea-9992-af49c31821ad.gif)

**Comment by jordantsap** [comment]
uname -a
Linux parrot 5.4.0-2parrot1-amd64 #1 SMP Parrot 5.4.8-2parrot1 (2020-01-12) x86_64 GNU/Linux
$ php -v
PHP 7.3.12-1 (cli) (built: Nov 28 2019 07:34:08) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.12, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.12-1, Copyright (c) 1999-2018, by Zend Technologies

**Comment by jordantsap** [comment]
There is something wrong with the banner command in the var.php file. Commenting that line in the main file runs as it should without displaying the banner though

**Comment by nandydark** [comment]
thnx for telling the error,  now you can reinstall dark-eagle and use it, the problem is now sorted out...

**Comment by jordantsap** [comment]
There is no installation included. you just clone it and run the script, i only need git pull

**Comment by nandydark** [comment]
> There is no installation included. you just clone it and run the script, i only need git pull

u wanna fork then u can but i will not allow pull!!!!!!!!

**Comment by jordantsap** [comment]
There is no change same thing happens

**Comment by nandydark** [comment]
> There is no change same thing happens

send pic or video

**Comment by jordantsap** [comment]
> > There is no installation included. you just clone it and run the script, i only need git pull
> 
> u wanna fork then u can but i will not allow pull!!!!!!!!

I did already i think but that's not thwe problem

> > There is no change same thing happens
> 
> send pic or video

HP Fatal error:  Uncaught Error: Call to undefined function darkeagle_banner() in /home/crescento/Pentest/DARK-EAGLE/darkeagle.php:7
Stack trace:
#0 {main}
  thrown in /home/crescento/Pentest/DARK-EAGLE/darkeagle.php on line 7
┌─[✗]─[user@parrot]─[~/Pentest/DARK-EAGLE]
└──╼ $

**Comment by jordantsap** [comment]
You have different banner function names decide which to keep
darkeagle_banner in the main script
eagledark_banner in var.php

**Comment by jordantsap** [comment]
Keeping darkeagle_banner() works as it should

**Comment by nandydark** [comment]
> You have different banner function names decide which to keep
> darkeagle_banner in the main script
> eagledark_banner in var.php

yaa reinstall it.. now

**Comment by nandydark** [comment]
hope the error is cleared.. nd reply if the error is cleared or not..

**Comment by jordantsap** [comment]
I changed the error reporting() to 1 in order to see whats happened and i just changed the name of the functrion to my local dir, now it works,

**Comment by nandydark** [comment]
> I changed the error reporting() to 1 in order to see whats happened and i just changed the name of the functrion to my local dir, now it works,

send pic wht u done..

**Comment by jordantsap** [comment]
It's in my forks now

**Comment by nandydark** [comment]
ya but don't remove my credits and ownership from my script bcz it is in under licence

**Comment by jordantsap** [comment]
Sure, i just deleted the whitespaces and some newlines

**Comment by jordantsap** [comment]
I dont think it's showing correct though,
I runned the A FLAG to my laravel site it uses apache but the script udentifyed nginx.
Everything else was correct

**Comment by nandydark** [comment]
> I dont think it's showing correct though,
> I runned the A FLAG to my laravel site it uses apache but the script udentifyed nginx.
> Everything else was correct

okay upload its pic or video here..

**Comment by jordantsap** [comment]
I just told you what the issue is
I don't find it wise to give you all my details here but tell me what info do you want more?
